// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel VSMCompute

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
Texture2D _InputTexture;
RWTexture2D<float4> _Result;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

    _Result[id.xy] = _InputTexture[id.xy] / 2.0;
}
